[workspace]
members = [
    "bin/tonic",
    "crates/p2p",
    "crates/primitives",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Ahmet Yazici"]
repository = "https://github.com/yaziciahmet/tonic"

[workspace.dependencies]
# Tonic dependencies
tonic = { path = "bin/tonic" }
tonic-p2p = { path = "crates/p2p" }
tonic-primitives = { path = "crates/primitives" }

# Common dependencies
anyhow = "1.0.90"
futures = "0.3"
serde = "1"
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
tokio = { version = "1.40", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
