[workspace]
members = [
    "bin/tonic",
    "crates/p2p",
    "crates/types",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Ahmet Yazici"]
repository = "https://github.com/yaziciahmet/tonic"

[workspace.dependencies]
futures = "0.3.31"
sha2 = "0.10"
tokio = { version = "1.40", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
