[package]
name = "tonic-primitives"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
hex = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }

[features]
default = []
test-helpers = ["dep:rand"]
