[package]
name = "tonic-primitives"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
hex = { workspace = true }
primitive-types = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true }
thiserror = { workspace = true }
tonic-crypto-utils = { workspace = true, features = ["keccak256", "secp256k1"] }

[features]
default = []
test-helpers = ["dep:rand", "tonic-crypto-utils/test-helpers"]
