[package]
name = "tonic"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["std", "fmt"] }

[[bin]]
name = "tonic"
path = "src/main.rs"

[lib]
name = "tonic"
path = "src/lib.rs"
