[package]
name = "tonic"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
tonic-tracing = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "tonic"
path = "src/main.rs"

[profile.release]
opt-level = 3
debug = 1
lto = true
codegen-units = 1
