[package]
name = "tonic-consensus"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]

[features]
default = []
test-helpers = []
