[package]
name = "tonic-txpool"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
tonic-primitives = { workspace = true }

[features]
default = []
