[package]
name = "tonic-p2p"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
libp2p = { version = "0.54", default-features = false, features = [
  "gossipsub",
  "identify",
  "kad",
  "macros",
  "noise",
  "secp256k1",
  "tcp",
  "tokio",
  "yamux",
] }
sha2 = { workspace = true }
tokio = { workspace = true }
tonic = { path = "../../bin/tonic" }
tracing = { workspace = true }
