[package]
name = "tonic-p2p"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
libp2p = { version = "0.54", default-features = false, features = [
  "gossipsub",
  "identify",
  "kad",
  "macros",
  "noise",
  "secp256k1",
  "tcp",
  "tokio",
  "yamux",
] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tonic = { workspace = true }

[features]
default = []
test-helpers = []
